language: python
python:
  - "2.6"
  - "2.7"
addons:
  apt:
    packages:
    - time
install:
  - "easy_install -U setuptools"
  - "pip install nose mock"
  - "pip install -e .[openstack,ec2,daemon]"
script: nosetests -v
